const path = require('path');
const chalk = require('chalk');
const tmp = require('tmp');
const dircompare = require('dir-compare');
const writeDocs = require('../../tasks/docs/writeDocs');

describe('docs', function() {
  it('are up-to-date (slow)', function() {
    this.timeout(20 * 1000);
    const tmpDir = tmp.dirSync({
      unsafeCleanup: true,
    });

    const writeAndCompare = writeDocs(tmpDir.name, false)
      .then(function() {
        const results = dircompare.compareSync(path.resolve('./docs'), tmpDir.name, {
          compareContent: true,
        });

        tmpDir.removeCallback();

        return results;
      });

    return expect(writeAndCompare).to.eventually.have
      .property('same', true, 'Docs need regenerated by running ' + chalk.cyan('gulp docs') + '.');
  });
});
