name: Automatic Rebase

on: [pull_request_target]

jobs:
  _:
    name: "Automatic Rebase"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ljharb/rebase@c6bd0a72b14dfaf76ad6a070029c8b4592d03eea # master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
